language: java
sudo: false
jdk:
  - openjdk8
before_script:
  - chmod +x gradlew
cache:
  directories:
    - "$HOME/.gradle/caches/"
    - "$HOME/.gradle/wrapper/"
deploy:
  provider: script
  script: ./gradlew clean assemble bintrayUpload
  skip_cleanup: true # to upload artifacts created during the build
  dry-run: false
  on:
    branch: master