-- begin MWATTREPS_ATTACHMENT
alter table MWATTREPS_ATTACHMENT add constraint FK_MWATTREPS_ATTACHMENT_ON_FILE foreign key (FILE_ID) references SYS_FILE(ID)^
alter table MWATTREPS_ATTACHMENT add constraint FK_MWATTREPS_ATTACHMENT_ON_TYPE foreign key (TYPE_ID) references MWATTREPS_ATTACHMENT_TYPE(ID)^
alter table MWATTREPS_ATTACHMENT add constraint FK_MWATTREPS_ATTACHMENT_ON_REPORT foreign key (REPORT_ID) references REPORT_REPORT(ID)^
create index IDX_MWATTREPS_ATTACHMENT_ON_FILE on MWATTREPS_ATTACHMENT (FILE_ID)^
create index IDX_MWATTREPS_ATTACHMENT_ON_TYPE on MWATTREPS_ATTACHMENT (TYPE_ID)^
create index IDX_MWATTREPS_ATTACHMENT_ON_REPORT on MWATTREPS_ATTACHMENT (REPORT_ID)^
-- end MWATTREPS_ATTACHMENT
